
services:
  # SQL Server - Cơ sở dữ liệu
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: lms_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - lms_sql_data:/var/opt/mssql

  # Backend - Ứng dụng ASP .NET Core
  backend:
    build:
      context: ./LMS.BE
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"             # host:container
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EnableHttpsRedirection=false
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=LMS;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;

  # Frontend - Ứng dụng ReactJS
  frontend:
    build:
      context: ./LMS.FE
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8080/api
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  lms_sql_data:
